package com.example.demo.persistance.entities;
// Generated 29 avr. 2021 � 09:00:55 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AfpaSanction generated by hbm2java
 */
@Entity
@Table(name = "AFPA_SANCTION", schema = "TPGESTIONRH")
public class AfpaSanction implements java.io.Serializable {

	private BigDecimal refSanction;
	private AfpaEmployeweb afpaEmployeweb;
	private String description;
	private String typeSanction;

	public AfpaSanction() {
	}

	public AfpaSanction(BigDecimal refSanction) {
		this.refSanction = refSanction;
	}

	public AfpaSanction(BigDecimal refSanction, AfpaEmployeweb afpaEmployeweb, String description,
			String typeSanction) {
		this.refSanction = refSanction;
		this.afpaEmployeweb = afpaEmployeweb;
		this.description = description;
		this.typeSanction = typeSanction;
	}

	@Id

	@Column(name = "REF_SANCTION", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getRefSanction() {
		return this.refSanction;
	}

	public void setRefSanction(BigDecimal refSanction) {
		this.refSanction = refSanction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_EMP")
	public AfpaEmployeweb getAfpaEmployeweb() {
		return this.afpaEmployeweb;
	}

	public void setAfpaEmployeweb(AfpaEmployeweb afpaEmployeweb) {
		this.afpaEmployeweb = afpaEmployeweb;
	}

	@Column(name = "DESCRIPTION", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "TYPE_SANCTION", length = 20)
	public String getTypeSanction() {
		return this.typeSanction;
	}

	public void setTypeSanction(String typeSanction) {
		this.typeSanction = typeSanction;
	}

}
