package com.example.demo.persistance.entities;
// Generated 29 avr. 2021 � 09:00:55 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AfpaAbsence generated by hbm2java
 */
@Entity
@Table(name = "AFPA_ABSENCE", schema = "TPGESTIONRH")
public class AfpaAbsence implements java.io.Serializable {

	private BigDecimal idabsence;
	private AfpaEmployeweb afpaEmployeweb;
	private BigDecimal nbjours;
	private String motif;
	private String justificatif;

	public AfpaAbsence() {
	}

	public AfpaAbsence(BigDecimal idabsence) {
		this.idabsence = idabsence;
	}

	public AfpaAbsence(BigDecimal idabsence, AfpaEmployeweb afpaEmployeweb, BigDecimal nbjours, String motif,
			String justificatif) {
		this.idabsence = idabsence;
		this.afpaEmployeweb = afpaEmployeweb;
		this.nbjours = nbjours;
		this.motif = motif;
		this.justificatif = justificatif;
	}

	@Id

	@Column(name = "IDABSENCE", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdabsence() {
		return this.idabsence;
	}

	public void setIdabsence(BigDecimal idabsence) {
		this.idabsence = idabsence;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_EMP")
	public AfpaEmployeweb getAfpaEmployeweb() {
		return this.afpaEmployeweb;
	}

	public void setAfpaEmployeweb(AfpaEmployeweb afpaEmployeweb) {
		this.afpaEmployeweb = afpaEmployeweb;
	}

	@Column(name = "NBJOURS", precision = 22, scale = 0)
	public BigDecimal getNbjours() {
		return this.nbjours;
	}

	public void setNbjours(BigDecimal nbjours) {
		this.nbjours = nbjours;
	}

	@Column(name = "MOTIF", length = 50)
	public String getMotif() {
		return this.motif;
	}

	public void setMotif(String motif) {
		this.motif = motif;
	}

	@Column(name = "JUSTIFICATIF", length = 20)
	public String getJustificatif() {
		return this.justificatif;
	}

	public void setJustificatif(String justificatif) {
		this.justificatif = justificatif;
	}

}
