package com.example.demo.persistance.entities;
// Generated 29 avr. 2021 � 09:00:55 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AfpaConge generated by hbm2java
 */
@Entity
@Table(name = "AFPA_CONGE", schema = "TPGESTIONRH")
public class AfpaConge implements java.io.Serializable {

	private BigDecimal refConge;
	private AfpaEmployeweb afpaEmployeweb;
	private Date dateDebut;
	private Date dateFin;
	private Date dateDemande;
	private BigDecimal soldeConge;

	public AfpaConge() {
	}

	public AfpaConge(BigDecimal refConge) {
		this.refConge = refConge;
	}

	public AfpaConge(BigDecimal refConge, AfpaEmployeweb afpaEmployeweb, Date dateDebut, Date dateFin, Date dateDemande,
			BigDecimal soldeConge) {
		this.refConge = refConge;
		this.afpaEmployeweb = afpaEmployeweb;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
		this.dateDemande = dateDemande;
		this.soldeConge = soldeConge;
	}

	@Id

	@Column(name = "REF_CONGE", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getRefConge() {
		return this.refConge;
	}

	public void setRefConge(BigDecimal refConge) {
		this.refConge = refConge;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_EMP")
	public AfpaEmployeweb getAfpaEmployeweb() {
		return this.afpaEmployeweb;
	}

	public void setAfpaEmployeweb(AfpaEmployeweb afpaEmployeweb) {
		this.afpaEmployeweb = afpaEmployeweb;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_DEBUT", length = 7)
	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_FIN", length = 7)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_DEMANDE", length = 7)
	public Date getDateDemande() {
		return this.dateDemande;
	}

	public void setDateDemande(Date dateDemande) {
		this.dateDemande = dateDemande;
	}

	@Column(name = "SOLDE_CONGE", precision = 22, scale = 0)
	public BigDecimal getSoldeConge() {
		return this.soldeConge;
	}

	public void setSoldeConge(BigDecimal soldeConge) {
		this.soldeConge = soldeConge;
	}

}
