package com.example.demo.persistance.entities;
// Generated 29 avr. 2021 � 09:00:55 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AfpaEmployeweb generated by hbm2java
 */
@Entity
@Table(name = "AFPA_EMPLOYEWEB", schema = "TPGESTIONRH")
public class AfpaEmployeweb implements java.io.Serializable {

	private BigDecimal code;
	private BigDecimal salaire;
	private String numtel;
	private String nom;
	private String prenom;
	private String adresse;
	private Set<AfpaConge> afpaConges = new HashSet<AfpaConge>(0);
	private Set<AfpaSanction> afpaSanctions = new HashSet<AfpaSanction>(0);
	private Set<AfpaAbsence> afpaAbsences = new HashSet<AfpaAbsence>(0);

	public AfpaEmployeweb() {
	}

	public AfpaEmployeweb(BigDecimal code) {
		this.code = code;
	}

	public AfpaEmployeweb(BigDecimal code, BigDecimal salaire, String numtel, String nom, String prenom, String adresse,
			Set<AfpaConge> afpaConges, Set<AfpaSanction> afpaSanctions, Set<AfpaAbsence> afpaAbsences) {
		this.code = code;
		this.salaire = salaire;
		this.numtel = numtel;
		this.nom = nom;
		this.prenom = prenom;
		this.adresse = adresse;
		this.afpaConges = afpaConges;
		this.afpaSanctions = afpaSanctions;
		this.afpaAbsences = afpaAbsences;
	}

	@Id

	@Column(name = "CODE", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getCode() {
		return this.code;
	}

	public void setCode(BigDecimal code) {
		this.code = code;
	}

	@Column(name = "SALAIRE", precision = 22, scale = 0)
	public BigDecimal getSalaire() {
		return this.salaire;
	}

	public void setSalaire(BigDecimal salaire) {
		this.salaire = salaire;
	}

	@Column(name = "NUMTEL", length = 20)
	public String getNumtel() {
		return this.numtel;
	}

	public void setNumtel(String numtel) {
		this.numtel = numtel;
	}

	@Column(name = "NOM", length = 20)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM", length = 20)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "ADRESSE", length = 20)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "afpaEmployeweb")
	public Set<AfpaConge> getAfpaConges() {
		return this.afpaConges;
	}

	public void setAfpaConges(Set<AfpaConge> afpaConges) {
		this.afpaConges = afpaConges;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "afpaEmployeweb")
	public Set<AfpaSanction> getAfpaSanctions() {
		return this.afpaSanctions;
	}

	public void setAfpaSanctions(Set<AfpaSanction> afpaSanctions) {
		this.afpaSanctions = afpaSanctions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "afpaEmployeweb")
	public Set<AfpaAbsence> getAfpaAbsences() {
		return this.afpaAbsences;
	}

	public void setAfpaAbsences(Set<AfpaAbsence> afpaAbsences) {
		this.afpaAbsences = afpaAbsences;
	}

}
